### ISSUE TITLE
Create a compact version of editor/result layout so that it could be embedded into web pages

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#12]
Let's say jsfiddle allows you to embed fiddle inside any html page, a good example could be found in this blog: http://blog.stevensanderson.com/2011/12/21/knockout-2-0-0-released/, search for "1. Control flow bindings" to see the fiddles embedded.

With this feature ready I could embed rythm fiddles into the rythm document, brings great user interaction experience when they read the document

**Comment by greenlaw110** [comment]
Here is a draft wireframe for compact fiddle UI: https://www.wireframes.org/ui/mt.php?pa=compact_fiddle_51501b71f2fb3

**Comment by freewind** [comment]
I don't have access to this url: https://www.wireframes.org/ui/mt.php?pa=compact_fiddle_51501b71f2fb3

**Comment by greenlaw110** [comment]
hmm... looks like it needs pro version to publish the design. Here is the screen capture: http://ge.tt/8rb595c/v/0

**Comment by freewind** [comment]
OK, I'll try it

**Comment by greenlaw110** [comment]
great!

**Comment by freewind** [comment]
You can see there is an "eye" button on the left, beside "new file...", when you click it, a new compact view will be opened on the new window.

You can use "iframe" in you demo page with that url to embed the demo.

PS: In your draft wireframe, you said when double click on a tab head, user can edit the file name, but it's not easy to implement it with angular-bootstrap library. Instead, I put those buttons on the top right.

Please have a try and give me more advice.

**Comment by greenlaw110** [comment]
Hey you've just done an awesome work! Really appreciate that. There are several minor bugs in the compact mode and I've submitted as an new issue. But yes, this is a great feature and thanks for your dedication!

**Comment by freewind** [comment]
:) I will try to fix them soon.
