### ISSUE TITLE
Add icon to embedded view tabs

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#15]
Use [fontawesome](http://fortawesome.github.com/Font-Awesome/) to add icons to tab headers

For Result tab, use "icon-eye-open" or "icon-play"

For Template tab, use "icon-file-alt"

**Comment by freewind** [comment]
Which is not easy unless I hack the [angular-ui/bootstrap](https://github.com/angular-ui/bootstrap). 

I just request a feature: https://github.com/angular-ui/bootstrap/issues/268

Do you have any easy solution without hack?

**Comment by greenlaw110** [comment]
I've sent the pull request as issue #17
