### ISSUE TITLE
Clicking on Run button in editor view doesn't respond

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#18]
Go to http://fiddle.rythmengine.org/editor/590e5d475704421db16e59b16bb1730a, make any changes in either template or params, the run button color changed, that's good. However clicking on it doesn't trigger an ajax call back to server and thus nothing happened.

Note there is no error logged in console, it simply doesn't work

**Comment by greenlaw110** [comment]
I've also noticed when I "new" an new case if I logged in as an admin, the run button works at the first time, but the following clicks will fail

**Comment by freewind** [comment]
I'm afraid I have to write tests now, the javascript code is too easy to break, especially when I share one controller between two pages.
