### ISSUE TITLE
Embedded view doesn't work in IE 10 (and probably IE 9 also)

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#19]
It's caused in CodeMirror JS:

![Capture](https://f.cloud.github.com/assets/216930/301453/9ea0b580-95d4-11e2-9a39-c76a7e5eb1ce.PNG)

**Comment by greenlaw110** [comment]
The error is triggered when I click on "Result" tab in IE 10

**Comment by freewind** [comment]
I just found other issues, that whenever which tab I clicked, the code-mirror editor is always the same one.

I'm afraid it's not easy to fix it.

**Comment by freewind** [comment]
I found another approach to workaround that issue. Now it works on IE9
