### ISSUE TITLE
The "Note: you can use..." message show be hidden when switch to Result view 

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#22]
![Capture](https://f.cloud.github.com/assets/216930/305255/c8d43c4e-9653-11e2-8c86-c04a3309e4b9.PNG)

**Comment by greenlaw110** [comment]
BTW, do you need that "Run again" button?

**Comment by freewind** [comment]
If we show "params" textarea in the result view, "Run again" is useful since user can change the parameters to run it again. Shall we do it?

And sometimes, when switching to Result page, it may return a "Timeout" exception (in my computer), than I can click "Run again".

**Comment by greenlaw110** [comment]
sounds reasonable, let's get back the param box and keep the Run again
button, even we could make when focus leave the param box automatically run
it

**Comment by greenlaw110** [comment]
We probably need some visual indication, something like a spinner could be
fine to let the user know that it's running the template in the backend.
What do you think?

**Comment by freewind** [comment]
a "spinner" is a good idea, let me try to implement it

**Comment by greenlaw110** [comment]
try to use http://fortawesome.github.com/Font-Awesome/#icon/icon-spinner and
checkout http://fortawesome.github.com/Font-Awesome/#examples to see how to
make the icon auto-spin

**Comment by greenlaw110** [comment]
Hi I can still see the message "Note: you can use String,Integer,Boolean and most other JDK classes as argument types" in the result pane :(

**Comment by freewind** [comment]
I thought you agreed to show it there, ok, let me hide it.

**Comment by greenlaw110** [comment]
I agree to show param box there, but the notice has no use to end user. Or
do you have any other idea that we should display it?

**Comment by freewind** [comment]
No, just hide it :)
