### ISSUE TITLE
Allow press ctrl-enter trigger run the template

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#23]
When user are in template editor or param editor, press ctrl-enter to trigger template run and switch to the result pane automatically, if it is already in the result pane, re-run the template with new param.

**Comment by freewind** [comment]
There is a bug in "angular-ui", that `codeMirror` can't work with `uikeypress` : https://github.com/angular-ui/angular-ui/issues/517

So I have to make a dirty hack to "angular-ui.js". See my pushed code.
