### ISSUE TITLE
Is it possible to use different codemirror mode for different code mirror instance

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#29]
For example, I want to use rythm mode for template and javascript mode for params

**Comment by freewind** [comment]
By the way, I don't see the effect of `rythm-mode`, there is no highlight for `@` strings.

**Comment by greenlaw110** [comment]
There should be highlight to @ leading strings, checkout http://rythmengine.org/doc/feature. However rythm template is fairly complicated, the current implementation of rythm-mode is very limited. For now I will keep it as it is. I will back to the user manual documentation and hope I can get it done in 2 days.
