### ISSUE TITLE
Add a index to sample code view

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#34]
Add index to sample code. The index could be aggregated at the top left corner of the page, could be something like the index shown in http://rythmengine.org/doc/expression.md

**Comment by freewind** [comment]
Which page should I add the indexes?

**Comment by greenlaw110** [comment]
http://fiddle.rythmengine.org/#/sample_model_code

**Comment by freewind** [comment]
Which bootstrap component ( or other plugin ) should I use? I just checked the bootstrap, but not get the idea.

**Comment by greenlaw110** [comment]
I use http://twitter.github.com/bootstrap/javascript.html#affix in
http://rythmengine.org/doc/feature and other rythm doc page. You can check
https://github.com/greenlaw110/rythm-website/blob/master/app/rythm/Doc/load.html
to
see how it is used in rythm website doc load template

**Comment by freewind** [comment]
There is too much work to do to implement affix with angularjs, since it uses `<a href="#target"` which should be handled in angularjs.

At last, I use traditional way to implement it. With `position: fixed` and `scrollInView`.
