### ISSUE TITLE
Use tabbed navigation in editor, kind of like embed page

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#39]
I am trying to make editor style looks like embed page style. However I don't know how to change the template file list (at the left navigation panel) into the tabbed navigation like the embed page, can you help with that?

**Comment by freewind** [comment]
Which page? Do you mean http://rythmfiddle.gelinsoft.com/#/editor ?

What do you want it look like? Exactly the same as embed page?

**Comment by greenlaw110** [comment]
Yes editor page. Here is the wireframe: http://ge.tt/4jhf13d/v/0

**Comment by greenlaw110** [comment]
Actually use this wireframe please: http://ge.tt/7afm23d/v/0?c
