### ISSUE TITLE
Add a about dialog

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#7]
Add a link "About" in the top bar, when clicking on it a dialog should pop up dialog, show the information about this web site including introduction, author and license info

**Comment by freewind** [comment]
Added. Please modify the information if needed

**Comment by greenlaw110** [comment]
Code reference: https://github.com/freewind/rythmfiddle/commit/a18f8572b70070cdcfac790b7c74cc51a5a133f8
